### ISSUE TITLE
consider splitting apart functionalities and avoid floating point operations to make code smaller

### ISSUE THREAD

**Issue by bxparks** [Naguissa/uRTCLib#10]
Hi,
In the spirit of sharing (since you made some suggestions on my project), when I scanned through your code, I noticed a few things. It's free advice, feel free to ignore :-)

1) Your chip model is selected at runtime through the `_model` parameter. That means that if the user is using only one type of chip, the code for the other chips are compiled into the binary and taking up flash memory, even if those other chips are never used. (It's possible that a very smart compiler will notice that the `_model` variable is actually  a compile-time constant if it is never modified after initialization, and remove the dead code, but I don't think the Arduino compilers are that smart.)

2) Somewhat related to (1), if a user is interested in only the time, but not the alarm function, the uRTCLib pulls in all the parameters for the alarm, even if the user never uses that function. Maybe consider splitting  functionalities (e.g. time, alarm, square wave) so that the user pays only for what they use.

3) The `temp()` function returns a float. Unfortunately, floating operations on microcontrollers without hardware FPU are expensive, both in CPU cycles and flash memory. On 8-bit AVR, your '/ 4.0' division operation brings in an extra 400 bytes of flash. On the 32-bit SAMD21, `float` and `double` are different types, float is 4 bytes and double is 8 bytes. A '/ 4.0f' operation consumes 720 bytes of extra flash and a '/ 4.0' (double operation like you have in your code) consumes 1450 extra bytes of flash. My suggestion is that the temperature remain in the native 8.8 fixed point representation, and you can provide helper methods to convert that to (signed whole degrees) and (fractional degrees).

**Comment by Naguissa** [comment]
1. I was planning to do so when I have time, because I think nobody uses more than 1 RTC at once.

2. Linker removes any unused code so it's not a problem (tested one year ago).

3. Very good idea, I will implement any kind of fixed point. I'll look at datasheets if I can fit it in one byte; if not I'll use suggested 2 bytes.


Thanks!

**Comment by bxparks** [comment]
2) Yes, the code will be removed by the linker, but I was actually referring to the `_a1_*` and other variables in your `uRTCLib` class. I'm pretty sure those are not removed by the linker even if there is no code that uses them. One could argue that 10-15 bytes of RAM is not a big deal, but on a 2kB ATmega328P (or smaller on ATtiny chips), every byte can be important.

**Comment by Naguissa** [comment]
3. Has been released just now. Very good point!


About 1 (and 2), I've reworked all code but I have one HUGE problem:

 - I don't want the user need to edit any file manually; I was thinking using defines....
 - But main program defines doesn't work well on libraries (as expected).

So the only way I've found is to include all support (different classes) and then use only one. But as it's a runtime variable/parameter linker cannot remove any code, as it doesn't know what one will be used when linking the library.

So, if I force one RTC chip I got a 5%-25% reduction (depending on the chip), but if I link all together I get a 25% increase in program size.

I've stored a copy of this process and will keep investigating (i.e.: I could use -D compiler parameter, but it's not any parameter used by average Arduino IDE user).

**Comment by bxparks** [comment]
Hi,

A few remarks...

A) I don't think your formula for calculating the temp is correct.. Let's say the temperature is 10.25 degrees, which the DS3231 returns as MSB=0x0A and LSB=0x40. Your formula is `(256* MSB + LSB/64) * 25 = (2560 + 1) * 25 =  64025`, which overflows the signed 16-bit integer, so I actually don't know what the compiler actually returns, probably -1511, but it's difficult to remember all the overflow rules in C/C++.

B) If you fixed this to the correct formula:
```C++
_temp = MSB * 100 + (LSB>>6)*25;
```
the problem is that the clients of the `temp()` function will need to do a `(temp / 100)` operation to get the whole number part of the temperature. But an 8-bit AVR does not have hardware integer division, so compiler will generate code for it, which takes about 200-250 clock cycles. In comparison, an 8-bit multiply is 1 clock cycle and a 16-bit integer multiply is 9 clock cycles. https://forum.arduino.cc/index.php?topic=92684.0

C) The other interesting thing about the temp from the DS3231 is negative temperature. It turns out that the DS3231 chip represents this as a *signed* 8.8 fixed point number, so if the temperature is -0.75C, the MSB is -1 (i.e. 0xFF) and the LSB is 0.25 (i.e. 0x40). Any encoding of the temperature needs to be able to handle negative temperatures.

D) Putting (B) and (C) together, it seems better to keep the temperature as a 8.8 signed fixed type, in other words, in units of 1/256 degrees C, then provide helper routines to extract the whole number and fractional number quickly. For example, the following:
```C++
// return the temperature as a signed integer in units of 1/256 degrees
int16_t temp() {
  ...
  return (int16_t) (msb << 8 | lsb);
}

// temperature in units of 1C
uint8_t whole_temp(int16_t temp) {
  if (temp < 0) temp = -temp;
  return (uint16_t) temp >> 8;
}

// fraction of temp in units of 0.01C, will always be 0, 25, 50 or 75
uint8_t frac_temp(int16_t temp) {
  if (temp < 0) temp = -temp;
  return ((uint8_t) temp >> 6) * 25;
}

// sign of temp, returns -1, 0, or 1
int8_t sign_temp(int16_t temp) {
  return (temp < 0) ? -1 : ((temp > 0) ? 1 : 0);
}
```
You can then use the 3 helper methods to provide a `print()` method that prints the temperature to `Serial` in a human readable form.

If you look at my code, that's essentially what my `printTo(Serial)` method does.


E) With regards to splitting the functionality, you probably need to consider using separate subclasses for each of the different RTC chips. This allows the user of the library to select the chip *at compile time*.

**Comment by Naguissa** [comment]
I have to check negative temp values (I'll need to put it inside freezer....), but positive values work perfectly. Take in mind it works in 2-complement base...

Also, with actual encoding I can use only one function to return any value; it can manage from 327.67 to -327.68 degrees, so I think it's not a problem.... 

About divission, I think temperature is not constantly used (it's updated every 53 seconds, as I recall), so I prefer giving it a good human readability. Using it it's not so intensive and that overhead (only on very simple MCUs, take in mind this library can be used in a wide range of MCUs, as STM32 or ESP8266) is negligible. I could use 8+8 bits fixed point, or any variation, but it will lead to worse readibility. At worst case, as an intnsive logging, you can use direct value and note it's degrees*100...

**Comment by bxparks** [comment]
That's a fair point that temp is not used often, so the division by 100 is not a big deal.
Looking over your formula again, I think I missed a pair of parenthesis. It now looks correct.
You can close this issue if you want.

**Comment by Naguissa** [comment]
Oh!

Well, I'll wait until I can test negative temp, now that my child is with grandparents and I can get back my laptop.... I can test on freezer now, bringing the tower and monitor downstairs didn't look as a good plan.... 😅

**Comment by Naguissa** [comment]
Seems negative values doesn't work OK. I'll check datasheet, maybe sensor is not capable, but this is not correct:

Freezer: -21ºC
Expected value: similar to -2100
Returned value:
RTC DateTime: 15/5/2 16:45:19 DOW: 6 - Temp: -15 - SRAM position 162 value: 0

**Comment by bxparks** [comment]
**Edit**: "left shift" -> "right shift"

I'm going to guess that the problem is the "right shift by 6" operation (`>> 6`) in your formula. If I recall, a right-shift of a signed integer for negative numbers is "implementation defined". On the microcontroller that you are using, the sign bit on a right shift may not be preserved. Try something like this instead:
```C++
_temp = (int16_t) (((uint16_t)MSB << 8) | (uint8_t)LSB) / 64 * 25;
```

**Comment by Naguissa** [comment]
To fix 2-complement I needed to add one if stament:


```
			MSB = Wire.read(); //2's complement int portion
			LSB = Wire.read(); //fraction portion
			_temp = 0b0000000000000000 | (MSB  << 2) | (LSB >> 6); // 8+2 bits, *25 is the same as number + 2bitdecimals * 100 in base 10
			if (MSB & 0b10000000) {
				_temp = (_temp | 0b1111110000000000);
				_temp--;
			}
			_temp = _temp * 25; // *25 is the same as number + 2bit (decimals) * 100 in base 10
```

Tested and new code works like a charm.

Thanks!

**Comment by Naguissa** [comment]
P.S.: Code commited and new release ... released. In few hours will be available on IDE's library manager.
