### ISSUE TITLE
STM32 - (ST core) - %hhu format specifiers aren't supported.

### ISSUE THREAD

**Issue by prosper00** [Naguissa/uRTCLib#15]
Tested and got this working on an STM32F103 (bluepill) board this afternoon. Works great, however, in several of your examples, you use the %hhu (printf) format specifier, which isn't supported by newlib nano on the official ST arduino core for the STM32 (not sure about the roger clark/maple core). Simply using %u seems to work OK however.

(although the STM32 has an onboard RTC, I was using a 3231)

**Comment by Naguissa** [comment]
Hello,

Thanks for the report.

I've tested compiling it and doesn't give me any warning. I have not tested on the board, so I don't know if it fails there. Is it the case?


Cheers.

**Comment by prosper00** [comment]
Yes, it compiles fine, however, the serial monitor literally prints "hu hu hu hu..."

**Comment by Naguissa** [comment]
Fixed on new release, 6.2.5


Thanks!
