### ISSUE TITLE
Day of week ISO 8601

### ISSUE THREAD

**Issue by BogdanovAleksei** [Naguissa/uRTCLib#22]
For European countries, the day of the week does not comply with ISO 8601

**Comment by Naguissa** [comment]
I've checked datasheets and there's no requirement, but on all datasheets the example included is Sun=1. Also, I've seen other libraries using the same encoding, so changing it will:
 - Break examples compatibility
 - Break other libraries compatibility / interoperability
 - Break compatibility / interoperability with sketches written with older version.

I'm spanish and we also use Mon..Sun, but I prefer to stitch to the majority in this case.


Cheers!
