### ISSUE TITLE
ds3232 clock frequency calibration via aging offset register

### ISSUE THREAD

**Issue by eleksir** [Naguissa/uRTCLib#23]
It is possible to achieve even more accuracy in timekeeping on ds3232 and it looks like it fair for ds3231 too.

http://www.kerrywong.com/2014/07/19/ds3232-clock-frequency-calibration/
If you happen to add this idea in your lib, it will be great.

**Comment by Naguissa** [comment]
Version 6.4.0 released.

Added agingGet and agingSet functions in order to control aging value on DS323X RTCs.

You can see its usage here: https://github.com/Naguissa/uRTCLib/blob/master/examples/uRTCLib_example_full/uRTCLib_example_full.ino#L64
