### ISSUE TITLE
UNIX Timestamp

### ISSUE THREAD

**Issue by TCB13** [Naguissa/uRTCLib#29]
Hello,

Are there any plans to implement a method that will output a UNIX timestamp as an int? This would be very helpful since using timestamps is way easier than full dates.

Thank you.

**Comment by Naguissa** [comment]
Not really. There're other mature projects for doing so in library manager, like TimeLib: https://github.com/PaulStoffregen/Time

**Comment by TCB13** [comment]
I was trying to avoid TimeLib because of its size. Having it builtin into uRTCLib was probably just a few lines of code without much impact on this library and a huge upside.

**Comment by Naguissa** [comment]
I've seen how Adafruit does it; do you think it could be interesting?

https://github.com/adafruit/RTClib/blob/master/src/RTClib.cpp

**Comment by TCB13** [comment]
Hello,

If we're talking about https://github.com/adafruit/RTClib/blob/master/src/RTClib.cpp#L568 and https://github.com/adafruit/RTClib/blob/master/src/RTClib.cpp#L129 that's interesting.

Thank you.

**Comment by Naguissa** [comment]
Done! https://github.com/Naguissa/uUnixDate


I'm requesting IDE insertion right now, may be in few days.

**Comment by TCB13** [comment]
@Naguissa thank you for the new lib!
