### ISSUE TITLE
Set time

### ISSUE THREAD

**Issue by k7ilo** [Naguissa/uRTCLib#30]
Hello

Not an issue but a question.  Does this library have commands that allow each parameter such as day, hour, minute, etc to be set individually?  I am working on an application that that feature would be great.

Thanks

**Comment by Naguissa** [comment]
Hello.

Old issue I overlooked., I'm sorry.


No, you need to set all parameters. But you have getters, so you can use set with all getters except desired one.

One characteristic is that it keeps internal  data and only updates it using refresh(), so using getters are not a problem.
