### ISSUE TITLE
Small typo found (lostPowerClear)

### ISSUE THREAD

**Issue by rtek1000** [Naguissa/uRTCLib#40]
Hello,

> the oscillator is enabled and time starts incermenting

incermenting ---> incREmenting

- Suggested by Google: "the oscillator is enabled and the time starts to increase"

https://github.com/Naguissa/uRTCLib/blob/b2863b61cf30ee0f7bef9a53117646e093786944/src/uRTCLib.cpp#L344C76-L344C130

**Comment by Naguissa** [comment]
Thanks. Fixed!
