### ISSUE TITLE
[Tip] Use DS3231 as RAM memory (NVRAM)

### ISSUE THREAD

**Issue by rtek1000** [Naguissa/uRTCLib#41]
The DS3231 does not have dedicated RAM like the DS3232 or DS1307.

But if it is just a few bytes, it is possible to use the DS3231 as NVRAM memory (non-volatile),

I used the alarm bytes as NVRAM memory and it worked. If I need to restart the uC, I can find the data there on the DS3231.

Obviously, if the alarms are being used for another purpose, it should not be possible to use them as NVRAM memory.

**Comment by Naguissa** [comment]
You can use it if you want, but then SQWG will act randomly so it's better to leave it unconnected.
